server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/slaticket
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  jwt:
    secret: iambatman!iamvengeance!
    expiration-ms: 3600000